# Generated by Django 4.2 on 2023-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("REC", "Records"),
                    ("CLT", "Clothing"),
                    ("PST", "Posters"),
                    ("MIS", "Miscellaneous"),
                ],
                default="REC",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
