# Generated by Django 4.2 on 2023-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_band_alter_band_year_formed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
    ]
